### PR TITLE
Add support for Package reference format and central package management

### LINKED ISSUE #36: Add support for Package reference format and Central Package Management (CPM)
**Is your feature request related to a problem? Please describe.**
It would be really neat if this project could support 
- projects specifying dependencies using [package reference format](https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)
- projects specifying dependencies using package reference format and [Central Package Management (CPM)](https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management)

**Describe the solution you'd like**
Dependency walker should be able to walk solutions that contains any or a mix of projects specifying dependencies with 
- packages.config files
- package reference format
- central package management

**Describe alternatives you've considered**
There isnt a whole lot of tooling that supports this which is exactly why it makes a lot of sense for the dependency walker to support the functionality.

**Additional context**
If one was hypothetically migrating a project from .net framework to .net, one of the steps is to migrate the project to use package reference format as a way of specifying dependencies. This means its likely that older projects getting migrated off .net framework could find use for support package ref format and cpm as a way of better understanding package use within a solution. 
A quick bit of extra info on Package ref format and Central Package ManagementCPM

### Package Reference Format
Dependencies are specified inside the .csproj file instead of the packages.config file. An example dependency specificiation might look like
```
<PackageVersion Include="Newtonsoft.Json" Version="13.0.1" />
```

### Central Package Management
A new file (```Directory.Packages.props```) is used to specify dependencies. This is shared between different csproj's within a repo (note that multiple solutions in the same repository can use the same props file). 

Example Dependency inside a .csproj:
```
 <PackageReference Include="Newtonsoft.Json" />
```
With version specified inside a Directory.Packages.Props file
```
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup
</Project>
```

### PR DESCRIPTION
**Pull request by Marethyu1**
Achieves this by adding logic to determine whether a project is using packages.config, package reference or package reference + central package management

once it understands which format it should be using it then resolves the nuget dependencies for the given format

This has been raised in relation to solving #36

### CODE REVIEW

**Comment by hanzworld** [comment]
The CodeQL and Analyze checks were not working at time of PR opening and the pull request won't trigger them without new commits. I'm closing and reopening this PR to retrigger the checks.

**Comment by hanzworld** [comment]
Aaand I should have remembered that reopening a PR doesn't retrigger checks 🤦‍♂️

**Comment by hanzworld** [comment]
Merging as the builds and unit tests pass.

**Comment by Marethyu1** [comment]
Hmm looks like one of the tests failed https://github.com/hanzworld/DependencyWalker/actions/runs/6712731519/job/18242884800 ill take a look when i get a mo

**Pull request merged**
